POST http://localhost:3001/register/
content-type: application/json

{
    "login": "user-to-delete",
    "password": "test123"
}

###

POST http://localhost:3001/login/
content-type: application/json

{
    "login": "user-to-delete",
    "password": "test123"
}

###

POST http://localhost:3001/logout/
content-type: application/json
