PUT http://localhost:3001/api/rooms/695e0e982d3d3e8ebd81d6a7
content-type: application/json

{
  "name": "Superior King Room with Balcony - Edited",
  "category": "superior",
  "size": "28",
  "bed": "1 king bed",
  "description": "This spacious, air-conditioned room features a balcony with a city view, a flat-screen TV with satellite channels, a seating area, a telephone, a refrigerator, a safety deposit box, ironing facilities and a private bathroom with a shower or a bath tub, a hairdryer and free toiletries.",
  "bathroom": [
    "Free toiletries",
    "Towels",
    "Shower",
    "Hairdryer",
    "Bathrobe",
    "Toilet paper",
    "Toilet"
  ],
  "view": "City view",
  "facilities": [
    "Balcony",
    "Heating",
    "Air conditioning",
    "Flat-screen TV",
    "Safe",
    "Carpeted",
    "Linens",
    "Electric kettle",
    "Socket near the bed",
    "Outdoor furniture",
    "Desk",
    "Cable channels",
    "Sitting area",
    "Wake-up service",
    "Soundproof",
    "Wardrobe or closet",
    "Refrigerator",
    "Telephone",
    "Ironing facilities",
    "Tea/Coffee maker",
    "Radio"
  ],
  "pictures": [ 
    "/uploads/rooms/superior-king-room/courtyard-superior-king-room-1.jpg",
    "/uploads/rooms/superior-king-room/courtyard-superior-king-room-2.jpg",
    "/uploads/rooms/superior-king-room/courtyard-superior-king-room-3.jpg",
    "/uploads/rooms/superior-king-room/courtyard-superior-king-room-4.jpg",
    "/uploads/rooms/superior-king-room/courtyard-superior-king-room-5.jpg"
    ]
}

###
POST http://localhost:3001/auth/register/
content-type: application/json

{
    "login": "user-to-delete",
    "password": "test123"
}

###
POST http://localhost:3001/auth/login/
content-type: application/json

{
    "email": "antons.filipovs@gmail.com",
    "password": "Filant.504120"
}

###
POST http://localhost:3001/auth/logout/
content-type: application/json


###
GET http://localhost:3001/api/room/categories/
content-type: application/json

###
GET http://localhost:3001/api/rooms/692e99507474acc9fadf9924
content-type: application/json

###
POST http://localhost:3001/api/rooms/692e99507474acc9fadf9924
content-type: application/json

{
    "user": "692553e4157fc6682d4654da",
    "adults": 2,
    "checkIn": "2025-12-16",
    "checkOut": "2025-12-23"
}

###
GET http://localhost:3001/api/rooms/reservations
content-type: application/json

{
    "userId": "69493764de53beba7ee253d9"
}

###
DELETE http://localhost:3001/api/rooms/reservations/694bfd1d25962a9c097eed43
content-type: application/json


###
GET http://localhost:3001/api/rooms?roomCategory=suite&checkIn=2025-01-10&checkOut=2025-01-15
content-type: application/json

###
GET http://localhost:3001/api/rooms/
content-type: application/json