POST http://localhost:3001/api/rooms/create/
content-type: application/json

{
  "img": "https://cf.bstatic.com/xdata/images/hotel/max1024x768/673136591.jpg?k=cc8231726510d5386588127c41ad1f0ab59d0077590d35b648eea7ca8e8efa6c&o=",
  "name": "Junior suite",
  "category": "suite",
  "size": "25",
  "description": "The air-conditioned twin room offers a flat-screen TV, soundproof walls, a tea and coffee maker, heating as well as an inner courtyard view. The unit has 2 beds.",
  "bathroom": [
    "Free toiletries",
    "Toilet",
    "Bathtub or shower",
    "Towels",
    "Hairdryer",
    "Toilet paper"
  ],
  "view": "Inner courtyard view",
  "facilities": [
    "Air conditioning",
    "Linens",
    "Socket near the bed",
    "Soundproof",
    "TV",
    "Telephone",
    "Heating",
    "Flat-screen TV",
    "Electric kettle",
    "Wake-up service",
    "Upper floors accessible by elevator",
    "Tea/Coffee maker"
  ],
  "bookings": [
    {
      "user": "692553e4157fc6682d4654da",
      "adults": 2,
      "checkIn": "2025-12-16",
      "checkOut": "2025-12-23"
    }
  ]
}

###

POST http://localhost:3001/auth/register/
content-type: application/json

{
    "login": "user-to-delete",
    "password": "test123"
}

###

POST http://localhost:3001/auth/login/
content-type: application/json

{
    "email": "antons.filipovs@gmail.com",
    "password": "Filant.504120"
}

###

POST http://localhost:3001/auth/logout/
content-type: application/json


###

GET http://localhost:3001/api/room/categories/
content-type: application/json

###

GET http://localhost:3001/api/rooms?roomCategory=suite&checkIn=2025-01-10&checkOut=2025-01-15
content-type: application/json

###

GET http://localhost:3001/api/rooms/692e99507474acc9fadf9924
content-type: application/json

###

POST http://localhost:3001/api/rooms/692e99507474acc9fadf9924/addBooking
content-type: application/json

{
    "user": "692553e4157fc6682d4654da",
    "adults": 2,
    "checkIn": "2025-12-16",
    "checkOut": "2025-12-23"
}

###
GET http://localhost:3001/api/rooms/reservations
content-type: application/json

{
    "userId": "69493764de53beba7ee253d9"
}

###

DELETE http://localhost:3001/api/rooms/reservations/694bfd1d25962a9c097eed43
content-type: application/json