export * from './home/Home';
export * from './register/Register';
export * from './login/Login';
export * from './room/Room';
export * from './reservations/Reservations';
export * from './occupancy/Occupancy';
export * from './forbidden/Forbidden';
export * from './admin-dashboard/AdminDashboard';
export * from './add-room/AddRoom';
